# See reference docs for details:
# https://config.travis-ci.com.
dist: bionic

services:
  - docker

language: go
go: 1.16.x

addons:
  apt:
    packages:
      - make

cache:
  yarn: true
  directories:
    - ./frontends/web/node_modules
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/Library/Caches/Homebrew

jobs:
  include:
    - stage: Linux
      os: linux
      script:
        - ./scripts/travis-ci.sh ci
        - ./scripts/travis-ci.sh android
        - ./scripts/travis-ci.sh qt-linux
        - ./scripts/travis_upload_nightlies.sh
    - stage: macOS
      os: osx
      script:
        - ./scripts/travis-ci.sh qt-osx
        - ./scripts/travis_upload_nightlies.sh
